SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Building](
[Id] [int] IDENTITY NOT NULL,
[CityId] [int] NOT NULL,
[CityMapId] [int] NULL,
[BuldingTypeId] [int] NOT NULL,
[Name] [nvarchar](1000) NULL,
[Level] [float] NOT NULL DEFAULT 0,
[Visitor] [int] NOT NULL DEFAULT 0,
[Employees] [int] NOT NULL DEFAULT 0,
[Maintenance] [float] NOT NULL DEFAULT 0,
[OnUpgrade] [int] NOT NULL DEFAULT 0,
[LastUpgrade] [datetime] NOT NULL DEFAULT 0
PRIMARY KEY CLUSTERED 
(
[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE TABLE [dbo].[BuildingType](
[Id] [int] IDENTITY NOT NULL,
[Name] [nvarchar](1000) NULL,
[BasePrice] [float] NOT NULL DEFAULT 0,
[BaseMaintenance] [float] NOT NULL DEFAULT 0
PRIMARY KEY CLUSTERED 
(
[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO
